//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterCms.Module.Sales.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SalesGlobalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SalesGlobalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterCms.Module.Sales.Content.Resources.SalesGlobalization", typeof(SalesGlobalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer created successfully.
        /// </summary>
        public static string CreateBuyer_CreatedSuccessfully_Message {
            get {
                return ResourceManager.GetString("CreateBuyer_CreatedSuccessfully_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product created successfully.
        /// </summary>
        public static string CreateProduct_CreatedSuccessfully_Message {
            get {
                return ResourceManager.GetString("CreateProduct_CreatedSuccessfully_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier created successfully.
        /// </summary>
        public static string CreateSupplier_CreatedSuccessfully_Message {
            get {
                return ResourceManager.GetString("CreateSupplier_CreatedSuccessfully_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit created successfully.
        /// </summary>
        public static string CreateUnit_CreatedSuccessfully_Message {
            get {
                return ResourceManager.GetString("CreateUnit_CreatedSuccessfully_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete buyer {0}?.
        /// </summary>
        public static string DeleteBuyer_Confirmation_Message {
            get {
                return ResourceManager.GetString("DeleteBuyer_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer deleted successfully..
        /// </summary>
        public static string DeleteBuyer_DeletedSuccessfully_Message {
            get {
                return ResourceManager.GetString("DeleteBuyer_DeletedSuccessfully_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete product &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteProduct_Confirmation_Message {
            get {
                return ResourceManager.GetString("DeleteProduct_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted successfully.
        /// </summary>
        public static string DeleteProduct_DeletedSuccessfully_Message {
            get {
                return ResourceManager.GetString("DeleteProduct_DeletedSuccessfully_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete supplier {0}?.
        /// </summary>
        public static string DeleteSupplier_Confirmation_Message {
            get {
                return ResourceManager.GetString("DeleteSupplier_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier deleted successfully..
        /// </summary>
        public static string DeleteSupplier_DeletedSuccessfully_Message {
            get {
                return ResourceManager.GetString("DeleteSupplier_DeletedSuccessfully_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete unit &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteUnit_Confirmation_Message {
            get {
                return ResourceManager.GetString("DeleteUnit_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit deleted successfully.
        /// </summary>
        public static string DeleteUnit_DeletedSuccessfully_Message {
            get {
                return ResourceManager.GetString("DeleteUnit_DeletedSuccessfully_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string EditPartner_IvalidEmail_Message {
            get {
                return ResourceManager.GetString("EditPartner_IvalidEmail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer with such a name already exists..
        /// </summary>
        public static string SaveBuyer_NotUniqueName_Message {
            get {
                return ResourceManager.GetString("SaveBuyer_NotUniqueName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier with such a name already exists..
        /// </summary>
        public static string SaveSupplier_NotUniqueName_Message {
            get {
                return ResourceManager.GetString("SaveSupplier_NotUniqueName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit with such a short title already exists..
        /// </summary>
        public static string SaveUnit_NotUniqueShortTitle_Message {
            get {
                return ResourceManager.GetString("SaveUnit_NotUniqueShortTitle_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit with such a title already exists..
        /// </summary>
        public static string SaveUnit_NotUniqueTitle_Message {
            get {
                return ResourceManager.GetString("SaveUnit_NotUniqueTitle_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SiteSettings_Buyers_Address_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Buyers_Address_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SiteSettings_Buyers_Email_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Buyers_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SiteSettings_Buyers_Name_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Buyers_Name_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string SiteSettings_Buyers_PhoneNumber_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Buyers_PhoneNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyers.
        /// </summary>
        public static string SiteSettings_Buyers_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Buyers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SiteSettings_Products_Name_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Products_Name_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string SiteSettings_Products_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Products_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string SiteSettings_Products_Unit_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Products_Unit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string SiteSettings_SalesPartnersMenuItem {
            get {
                return ResourceManager.GetString("SiteSettings_SalesPartnersMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string SiteSettings_SalesProductsMenuItem {
            get {
                return ResourceManager.GetString("SiteSettings_SalesProductsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string SiteSettings_SalesUnitsMenuItem {
            get {
                return ResourceManager.GetString("SiteSettings_SalesUnitsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SiteSettings_Suppliers_Address_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Suppliers_Address_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SiteSettings_Suppliers_Email_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Suppliers_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SiteSettings_Suppliers_Name_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Suppliers_Name_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string SiteSettings_Suppliers_PhoneNumber_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Suppliers_PhoneNumber_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string SiteSettings_Suppliers_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Suppliers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short title.
        /// </summary>
        public static string SiteSettings_Units_ShortTitle_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Units_ShortTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string SiteSettings_Units_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Units_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string SiteSettings_Units_Title_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Units_Title_Title", resourceCulture);
            }
        }
    }
}
